<a href="https://colab.research.google.com/github/nurfatahk/tahapan-preprocessing-data/blob/main/Hasil_ujikendaraanbermotor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #import library numpy untuk numerik
import pandas as pd #import pandas untuk file csv
from sklearn import tree #sklearn untuk import decision tree

In [ ]:
#membaca Dataset dari file ke pandas dataFrame
uji = pd.read_csv('hasilujikendaraanbermotor.csv', delimiter=',', header=0)

In [ ]:
uji.head()

tanggal_uji  ...   keterangan
0  2019-10-01  ...        Lulus
1  2019-10-01  ...        Lulus
2  2019-10-01  ...        Lulus
3  2019-10-01  ...  Tidak Lulus
4  2019-10-01  ...        Lulus

[5 rows x 8 columns]

In [ ]:
#mengubah kelas (kolom "keterangan") dari string ke Unique-Integer
uji["keterangan"] = pd.factorize(uji.keterangan)[0]
uji["nomor_kendaraan"] = pd.factorize(uji.nomor_kendaraan)[0]
uji["merek"] = pd.factorize(uji.merek)[0]
uji["bahan_bakar"] = pd.factorize(uji.bahan_bakar)[0]
uji["tipe"] = pd.factorize(uji.tipe)[0]
uji["keterangan"] = pd.factorize(uji.keterangan)[0]
uji["alat_uji"] = pd.factorize(uji.alat_uji)[0]


In [ ]:
uji.head()

tanggal_uji  nomor_kendaraan  merek  ...  tahun_pembuatan  alat_uji  keterangan
0  2019-10-01                0      0  ...             2017         0           0
1  2019-10-01                1      1  ...             2014         0           0
2  2019-10-01                2      1  ...             2018         0           0
3  2019-10-01                3      2  ...             2017         0           1
4  2019-10-01                4      2  ...             2017         0           0

[5 rows x 8 columns]

In [ ]:
print(uji) #untuk mengecek semua

     tanggal_uji  nomor_kendaraan  merek  ...  tahun_pembuatan  alat_uji  keterangan
0     2019-10-01                0      0  ...             2017         0           0
1     2019-10-01                1      1  ...             2014         0           0
2     2019-10-01                2      1  ...             2018         0           0
3     2019-10-01                3      2  ...             2017         0           1
4     2019-10-01                4      2  ...             2017         0           0
...          ...              ...    ...  ...              ...       ...         ...
1494  2019-10-15              286      0  ...             2018         6           0
1495  2019-10-15             1473     10  ...             2001        58           0
1496  2019-10-15             1474      0  ...             2018        33           0
1497  2019-10-15             1475      5  ...             2016        59           0
1498  2019-10-15             1476      6  ...             2015   

In [ ]:
uji = uji.drop(labels="tanggal_uji", axis=1)

In [ ]:
print(uji) #untuk mengecek semua

      nomor_kendaraan  merek  ...  alat_uji  keterangan
0                   0      0  ...         0           0
1                   1      1  ...         0           0
2                   2      1  ...         0           0
3                   3      2  ...         0           1
4                   4      2  ...         0           0
...               ...    ...  ...       ...         ...
1494              286      0  ...         6           0
1495             1473     10  ...        58           0
1496             1474      0  ...        33           0
1497             1475      5  ...        59           0
1498             1476      6  ...         5           2

[1499 rows x 7 columns]


In [ ]:
#mengubah dataframe ke array numpy
uji = uji.to_numpy()

In [ ]:
print(uji) #untuk mengecek semua

[[   0    0    0 ... 2017    0    0]
 [   1    1    0 ... 2014    0    0]
 [   2    1    0 ... 2018    0    0]
 ...
 [1474    0    1 ... 2018   33    0]
 [1475    5    1 ... 2016   59    0]
 [1476    6    1 ... 2015    5    2]]


In [ ]:
#membagi Dataset => 1300 baris data untuk training dan 199 baris data untuk testing
dataTraining = np.concatenate((uji[0:900, :], uji[1000:1400, :]),
                              axis=0) #data training ada 1300 baris data
dataTesting = np.concatenate((uji[900:1000, :], uji[1400:1499, :]),
                             axis=0) #data testing ada 199 baris data

In [ ]:
print(dataTraining)
len(dataTraining) #panjang data training

[[   0    0    0 ... 2017    0    0]
 [   1    1    0 ... 2014    0    0]
 [   2    1    0 ... 2018    0    0]
 ...
 [1377    3    1 ... 2017   47    0]
 [1378    3    1 ... 2016   47    2]
 [1379    3    1 ... 2016    1    0]]


1300

In [ ]:
print(dataTesting)
len(dataTesting) #panjang data testing

[[ 893    1    1 ... 2018   47    0]
 [ 894    3    1 ... 2014   47    0]
 [ 895    0    1 ... 2010    6    1]
 ...
 [1474    0    1 ... 2018   33    0]
 [1475    5    1 ... 2016   59    0]
 [1476    6    1 ... 2015    5    2]]


199

In [ ]:
#memecah dataset ke input data dan label
inputTraining = dataTraining[:, 0:6]
inputTesting = dataTesting[:, 0:6]
labelTraining = dataTraining[:, 6]
labelTesting = dataTesting[:, 6]
print(labelTraining)
len(labelTraining)

[0 0 0 ... 0 2 0]


1300

In [ ]:
#mendefinisikan decision tree classifier
model = tree.DecisionTreeClassifier()

In [ ]:
#mentraining Model
model = model.fit(inputTraining, labelTraining)

In [ ]:
#mempridiksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 2 0 0 1 0 0 0 1 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 2]
Hasil Prediksi :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 2 1 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 1 2 2 2 2 1 2 2 2 2 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 1 2 2
 2 2 1 2 2 2 1 2 0 0 1 2 2 0]


In [ ]:
#Menghitung Akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar : 94 data
prediksi Salah : 105 data
Akurasi : 47.23618090452261 %
